### ISSUE TITLE
Fixes to do on weka

### ISSUE THREAD

**Issue by cephasax** [cephasax/MLResearch#16]
- [x] prints no terminal do weka ou no terminal do java... nao estão ajudando nem a entender erros nem a saber e qual a situação atual do programa.
- [x] manipular instances e ter nome do arquivo
- [x] adicionar vetor de probabilidade ao final

**Comment by antonino-feitosa** [comment]
Irei desabilitar os prints durante a avaliação de um classificador no WEKA.
Todo objeto Instances possui um atributo chamado relationName que identifica a base de dados. O nome do arquivo é necessário sabendo disso?
Que vetor de probabilidade seria esse? É o do PBIL? Adicione um get que eu insiro no WEKA. Na verdade basta modificar o toString do classificador PBIL, o weka imprime o classificador na interface.

**Comment by cephasax** [comment]
No PbilAutoEns, quando dá stop no processo na interface do weka, o main  continua rodando no eclipse, provavelmente isso aconteça mesmo que seja executado por linha de comando.

o PopulationBasedIn... tá dando um erro no início, bom olhar @antonino-feitosa

**Comment by cephasax** [comment]
performed steps ta saindo do for com valor+1 e gera um missvalue no print final com 1 a mais.

se for 20 ele imprime 21...

**Comment by antonino-feitosa** [comment]
Não consegui reproduzir o erro, você especificar em quais condições o erro é gerado?
Também não consegui executar o PbilAutoEns com a base Iris, estoura a memória com um 1g de heap.
Corrigi o performedSteps.

**Comment by antonino-feitosa** [comment]
O erro é causado quando todas as soluções geradas são inválidas, assim, a população é vazia e não a melhor solução não pode ser comparada com a melhor solução da população.

Está faltando a classe RunAutoWeka, é necessário verificar se ela está presente no projeto anterior. Quando ela estiver disponível eu crio as classes de execução.

Inclui uma classe para avaliação das medidas final F-Measure, Recall e Precision.

**Comment by cephasax** [comment]
Sobre o fmeasure e recall massa.

Vou add jaja a runautoweka pq eu deletei elas

E vou corrigir o erro da comparaçao nesse caso da primeira soluçao ser vazia
